"""Markdown report generator for ArrakisEngine.

Generates weekly/monthly coach reports with game summaries,
ACPL trends, improvement areas, and annotated critical positions.
"""

import json
import logging
from collections import defaultdict
from datetime import datetime, timedelta
from pathlib import Path

from src.models import init_db

logger = logging.getLogger(__name__)

WEEKLY_TEMPLATE = """# Chess Coaching Report: {display_name}
**Period:** {period_start} to {period_end}
**Generated:** {generated_at}

---

## Summary
- **Games played:** {total_games}
- **Results:** {wins}W / {losses}L / {draws}D ({win_rate}% win rate)
- **Average rating of opponents:** {avg_opp_rating}

## Performance This Period

### Results by Time Control
{time_class_table}

### Rating Trend
- **Starting rating:** {start_rating}
- **Ending rating:** {end_rating}
- **Change:** {rating_change}

---

## Game-by-Game Results

{game_list}

---

## Analysis Highlights

### Average Centipawn Loss (ACPL)
- **This period:** {period_acpl}
{acpl_comparison}

### Move Quality Distribution
{move_quality_table}

### Weakest Game Phase
{phase_analysis}

---

## Top Improvement Areas

{improvement_areas}

---

## Critical Positions to Review

{critical_positions}

---

## Coaching Recommendations

{recommendations}

---

*Report generated by ArrakisEngine*
*Positions can be analyzed at: https://lichess.org/analysis/{{fen}}*
"""


def generate_report(player_username: str, period: str = "weekly",
                    output_dir: str = "reports", db_path: str | None = None) -> str:
    """Generate a coaching report for a player.

    Args:
        player_username: chess.com username
        period: "weekly" or "monthly"
        output_dir: directory to write the report
        db_path: optional database path

    Returns:
        Path to the generated report file.
    """
    conn = init_db(db_path)

    player = conn.execute(
        "SELECT * FROM players WHERE username = ?", (player_username,)
    ).fetchone()
    if not player:
        conn.close()
        raise ValueError(f"Player {player_username} not found")

    # Determine period
    now = datetime.now()
    if period == "weekly":
        period_start = (now - timedelta(days=7)).strftime("%Y-%m-%d")
        days = 7
    else:
        period_start = (now - timedelta(days=30)).strftime("%Y-%m-%d")
        days = 30
    period_end = now.strftime("%Y-%m-%d")

    # Fetch games in period
    games = conn.execute(
        """SELECT g.* FROM games g
        WHERE g.player_id = ? AND g.date_played >= ? AND g.date_played <= ?
        ORDER BY g.date_played""",
        (player["id"], period_start, period_end),
    ).fetchall()
    games = [dict(g) for g in games]

    if not games:
        conn.close()
        logger.info("No games in period for %s", player_username)
        # Generate minimal report
        report = f"# Chess Coaching Report: {player['display_name'] or player_username}\n\n"
        report += f"**Period:** {period_start} to {period_end}\n\n"
        report += "No games played in this period.\n"
        return _save_report(report, player_username, period, output_dir)

    # Gather analysis data
    game_ids = [g["id"] for g in games]
    placeholders = ",".join("?" * len(game_ids))

    all_moves = conn.execute(
        f"SELECT * FROM move_analysis WHERE game_id IN ({placeholders})",
        game_ids,
    ).fetchall()
    all_moves = [dict(m) for m in all_moves]

    moves_by_game = defaultdict(list)
    for m in all_moves:
        moves_by_game[m["game_id"]].append(m)

    # Coaching data
    coaching_data = {}
    coaching_rows = conn.execute(
        f"SELECT * FROM game_coaching WHERE game_id IN ({placeholders})",
        game_ids,
    ).fetchall()
    for c in coaching_rows:
        coaching_data[c["game_id"]] = dict(c)

    conn.close()

    # Compute report data
    wins = sum(1 for g in games if g["result"] == "win")
    losses = sum(1 for g in games if g["result"] == "loss")
    draws = sum(1 for g in games if g["result"] == "draw")
    total = len(games)
    win_rate = round(wins / total * 100, 1) if total else 0

    opp_ratings = [g["opponent_rating"] for g in games if g["opponent_rating"]]
    avg_opp = round(sum(opp_ratings) / len(opp_ratings)) if opp_ratings else "N/A"

    player_ratings = [g["player_rating"] for g in games if g["player_rating"]]
    start_rating = player_ratings[0] if player_ratings else "N/A"
    end_rating = player_ratings[-1] if player_ratings else "N/A"
    if isinstance(start_rating, int) and isinstance(end_rating, int):
        diff = end_rating - start_rating
        rating_change = f"+{diff}" if diff >= 0 else str(diff)
    else:
        rating_change = "N/A"

    # Time class table
    tc_stats = defaultdict(lambda: {"games": 0, "wins": 0, "losses": 0, "draws": 0})
    result_key = {"win": "wins", "loss": "losses", "draw": "draws"}
    for g in games:
        tc = g["time_class"] or "unknown"
        tc_stats[tc]["games"] += 1
        tc_stats[tc][result_key[g["result"]]] += 1

    tc_lines = ["| Time Control | Games | W | L | D | Win% |", "|---|---|---|---|---|---|"]
    for tc, s in sorted(tc_stats.items()):
        wr = round(s["wins"] / s["games"] * 100) if s["games"] else 0
        tc_lines.append(f"| {tc} | {s['games']} | {s['wins']} | {s['losses']} | {s['draws']} | {wr}% |")
    time_class_table = "\n".join(tc_lines)

    # Game list
    game_lines = []
    for g in games:
        emoji = {"win": "W", "loss": "L", "draw": "D"}[g["result"]]
        color = g["player_color"]
        opp_r = g["opponent_rating"] or "?"
        player_moves = [m for m in moves_by_game.get(g["id"], []) if m["side"] == g["player_color"]]
        if player_moves:
            acpl = round(sum(m["swing_cp"] or 0 for m in player_moves) / len(player_moves), 1)
        else:
            acpl = "N/A"
        game_lines.append(
            f"| {g['date_played']} | {color} | {opp_r} | **{emoji}** | {acpl} | {g['time_class']} |"
        )

    game_list = "| Date | Color | Opp Rating | Result | ACPL | Time |\n|---|---|---|---|---|---|\n"
    game_list += "\n".join(game_lines)

    # ACPL
    all_player_moves = [
        m for g in games
        for m in moves_by_game.get(g["id"], [])
        if m["side"] == g["player_color"]
    ]
    if all_player_moves:
        period_acpl = round(
            sum(m["swing_cp"] or 0 for m in all_player_moves) / len(all_player_moves), 1
        )
    else:
        period_acpl = "N/A"

    acpl_comparison = ""
    if isinstance(period_acpl, float):
        if period_acpl < 40:
            acpl_comparison = "- Excellent accuracy for this rating level!"
        elif period_acpl < 70:
            acpl_comparison = "- Good accuracy — room for improvement in critical moments"
        else:
            acpl_comparison = "- Higher than ideal — focus on checking for threats before each move"

    # Move quality
    quality = {"excellent": 0, "good": 0, "inaccuracy": 0, "mistake": 0, "blunder": 0}
    for m in all_player_moves:
        cls = m["classification"]
        if cls in quality:
            quality[cls] += 1
    total_m = sum(quality.values()) or 1

    mq_lines = ["| Classification | Count | % |", "|---|---|---|"]
    for cls in ["excellent", "good", "inaccuracy", "mistake", "blunder"]:
        pct = round(quality[cls] / total_m * 100, 1)
        mq_lines.append(f"| {cls.title()} | {quality[cls]} | {pct}% |")
    move_quality_table = "\n".join(mq_lines)

    # Phase analysis
    phases = {"opening": [], "middlegame": [], "endgame": []}
    for m in all_player_moves:
        mn = m["move_number"]
        if mn <= 15:
            phases["opening"].append(m["swing_cp"] or 0)
        elif mn <= 30:
            phases["middlegame"].append(m["swing_cp"] or 0)
        else:
            phases["endgame"].append(m["swing_cp"] or 0)

    phase_lines = []
    worst_phase = None
    worst_acpl = 0
    for phase_name in ["opening", "middlegame", "endgame"]:
        moves_list = phases[phase_name]
        if moves_list:
            acpl = round(sum(moves_list) / len(moves_list), 1)
            phase_lines.append(f"- **{phase_name.title()}:** ACPL {acpl} ({len(moves_list)} moves)")
            if acpl > worst_acpl:
                worst_acpl = acpl
                worst_phase = phase_name
    phase_analysis = "\n".join(phase_lines)
    if worst_phase:
        phase_analysis += f"\n\n**Focus area:** {worst_phase.title()} — this is where the most accuracy is lost."

    # Improvement areas
    improvement_lines = []
    if quality["blunder"] > 0:
        improvement_lines.append(
            f"1. **Blunder reduction:** {quality['blunder']} blunders this period. "
            f"Practice the \"Am I leaving anything hanging?\" check before every move."
        )
    if quality["mistake"] > 0:
        improvement_lines.append(
            f"2. **Reducing mistakes:** {quality['mistake']} mistakes. "
            f"Many come from missing opponent threats — try counting attacker vs defenders."
        )
    if worst_phase:
        improvement_lines.append(
            f"3. **{worst_phase.title()} play:** Highest ACPL ({worst_acpl}) in the {worst_phase}. "
            f"Targeted practice in this phase will yield the biggest improvement."
        )
    if not improvement_lines:
        improvement_lines.append("Great accuracy this period! Keep up the consistent play.")
    improvement_areas = "\n".join(improvement_lines)

    # Critical positions from coaching
    crit_lines = []
    for g in games:
        cd = coaching_data.get(g["id"])
        if cd and cd.get("critical_moments_json"):
            try:
                moments = json.loads(cd["critical_moments_json"])
                for moment in moments[:2]:  # Top 2 per game
                    crit_lines.append(
                        f"### Game on {g['date_played']} (vs {g['opponent_rating'] or '?'})\n"
                        f"- **Move {moment.get('move_number', '?')}** ({moment.get('side', '?')}): "
                        f"{moment.get('what_happened', '')}\n"
                        f"- **Better:** {moment.get('what_was_better', '')}\n"
                    )
            except (json.JSONDecodeError, TypeError):
                pass

    if crit_lines:
        critical_positions = "\n".join(crit_lines[:6])  # Max 6 positions
    else:
        critical_positions = "No coaching data available yet. Run `python main.py coach` after analysis completes."

    # Recommendations
    rec_lines = []
    for g in games:
        cd = coaching_data.get(g["id"])
        if cd and cd.get("practical_focus"):
            rec_lines.append(f"- {cd['practical_focus']}")
    if rec_lines:
        # Deduplicate similar recommendations
        seen = set()
        unique_recs = []
        for r in rec_lines:
            if r not in seen:
                seen.add(r)
                unique_recs.append(r)
        recommendations = "\n".join(unique_recs[:5])
    else:
        recommendations = "- Complete game analysis and coaching to get personalized recommendations."

    # Fill template
    report = WEEKLY_TEMPLATE.format(
        display_name=player["display_name"] or player_username,
        period_start=period_start,
        period_end=period_end,
        generated_at=now.strftime("%Y-%m-%d %H:%M"),
        total_games=total,
        wins=wins,
        losses=losses,
        draws=draws,
        win_rate=win_rate,
        avg_opp_rating=avg_opp,
        time_class_table=time_class_table,
        start_rating=start_rating,
        end_rating=end_rating,
        rating_change=rating_change,
        game_list=game_list,
        period_acpl=period_acpl,
        acpl_comparison=acpl_comparison,
        move_quality_table=move_quality_table,
        phase_analysis=phase_analysis,
        improvement_areas=improvement_areas,
        critical_positions=critical_positions,
        recommendations=recommendations,
    )

    return _save_report(report, player_username, period, output_dir)


def _save_report(report: str, username: str, period: str, output_dir: str) -> str:
    """Save report to file and return the path."""
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)

    date_str = datetime.now().strftime("%Y-%m-%d")
    filename = f"{username}_{period}_{date_str}.md"
    path = out / filename

    with open(path, "w") as f:
        f.write(report)

    logger.info("Report saved to %s", path)
    return str(path)
